# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

# PHP version used in first build configuration.
php:
    - "5.4"

# WordPress version used in first build configuration.
env:
    - WP_VERSION=4.1

# Next we define our matrix of additional build configurations to test against.
# The versions listed above will automatically create our first configuration,
# so it doesn't need to be re-defined below.

# WP_VERSION specifies the tag to use. The way these tests are configured to run
# requires at least WordPress 3.8. Specify "master" to test against SVN trunk.

# Note that Travis CI supports listing these above to automatically build a
# matrix of configurations, but we're being nice here by manually building a
# total of four configurations even though we're testing 4 versions of PHP
# along with 2 versions of WordPress (which would build 8 configs otherwise).
# This takes half as long to run while still providing adequate coverage.

matrix:
  include:
    - php: "5.5"
      env: WP_VERSION=4.1
    - php: "5.6"
      env: WP_VERSION=4.1


# Clones WordPress and configures our testing environment.
before_script:
    - export GIT_NAME=$(basename $(pwd))
    - export PLUGIN_SLUG="avh-framework"
    - git clone git://develop.git.wordpress.org/ /tmp/wordpress
# - git clone . "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
    - cd ..
    - mkdir -p "/tmp/wordpress/src/wp-content/mu-plugins/"
    - mv $GIT_NAME "/tmp/wordpress/src/wp-content/mu-plugins/$PLUGIN_SLUG"
    - mv "/tmp/wordpress/src/wp-content/mu-plugins/$PLUGIN_SLUG/avh-framework.php" "/tmp/wordpress/src/wp-content/mu-plugins"
    - cd /tmp/wordpress
    - git checkout $WP_VERSION
    - mysql -e "CREATE DATABASE wordpress_tests;" -uroot
    - cp wp-tests-config-sample.php wp-tests-config.php
    - sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
    - sed -i "s/yourusernamehere/travis/" wp-tests-config.php
    - sed -i "s/yourpasswordhere//" wp-tests-config.php
# Comment out the echo as this interferes with Sessions.
    - sed -i '61 s/^/\/\/ /' tests/phpunit/includes/bootstrap.php
    - cd "/tmp/wordpress/src/wp-content/mu-plugins/$PLUGIN_SLUG"


script: phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
